### ISSUE TITLE
match validator issue

### ISSUE THREAD

**Issue by DashRiprock** [ghiscoding/angular-validation#105]
I'm having an issue with the matching validator when using it for a confirm email field.  When the user tabs from the confirm field to the submit button then clicks, it throws a validation error even though they match.  Have you seen this before?

**Comment by ghiscoding** [comment]
Can't really help you without seeing code, please make a Plunker demo if you want help.

**Comment by DashRiprock** [comment]
ok, here's the link   http://plnkr.co/edit/GekSVrHjxDxuR5WFISuB?p=preview

When I type in a matching email in the second confirm textbox and click tab I get "Confirm Email Address : Confirmation field does not match specified field "Email Address"." in the validation summary even though they match.

Thanks for your help.
Billy

**Comment by ghiscoding** [comment]
Seems like there is something wrong somewhere in your code because if I take your 2 inputs and paste them into my [Plunker demo](http://plnkr.co/edit/jADq7H?p=preview) it works perfectly as you can see for both valid/invalid.

![invalid](https://cloud.githubusercontent.com/assets/643976/12692379/2d34a3ec-c6c4-11e5-9a1c-037d49efae5a.png)
![valid](https://cloud.githubusercontent.com/assets/643976/12692380/2d35ba66-c6c4-11e5-9a9b-2a472d89bda2.png)


You're probably affecting the Angular-Validation somehow. Perhaps you're pushing something to the ngModel of the email confirmation and because of $digest and/or timing issue the validation kicks in too late. Try to remove everything you could that potentially affect the ngModel of Email Confirmation. Remove all the extra you've added, like ngBlur and everything else. 

I do see something wrong anyway, the validation is suppose to kick in right away when doing onBlur but even though the error message appears 1sec after. The 1 sec is only in effect while user is typing (not to annoy the user) but should be cancelled (timer) on an onBlur event. So there's something wrong somewhere. 
If I were you, I would start from my Plunker and add 1 by 1 your extra features.

**Comment by ghiscoding** [comment]
I spent 2 hours on this and I'm not intending to spend more time. Though I did find partially your problem, you're dealing with multiple scope and you are you using a child scope when calling the `validationService` from inside your custom `fsmbValidate` directive. 

For troubleshooting purposes, I added a lot of console.log and with them, I finally found that you're dealing with multiple scopes and that both input do actually become valid (you can see the images). But your custom directive uses a different scope and doesn't pull the same data/value. 

![valid](https://cloud.githubusercontent.com/assets/643976/12693539/a13708e6-c6da-11e5-9532-9c582274b135.png)


Then if I add a console.log of the scope I'm dealing with inside my validate() function, I get 4 calls of the `Scope` object and another 4 calls of the `ChildScope` objects and so we really different scopes. The reason of why 4 sets? It's because you have in total 4 different validators, for example `validation="required|email"` has 2 validators.

![multiplescopes](https://cloud.githubusercontent.com/assets/643976/12693563/70e3a57c-c6db-11e5-9bb8-b57a7acff30c.png)

Then the final real problem is that inside the Angular-Validation `validateMatching()` at line 1604 of your plunker. It is able to get the other value (email) only in 1 of the 2 scopes. Not sure which one is which but no matter what, the value is only accessible in 1 of the scope.


At the end, I'm not sure why you're doing an extra directive with transclude and etc... but it seems that you're looking for troubles by doing that. If you find a better way to get the value inside my `validateMatching()` function then let me know but else than that I can't help you more or actually don't want to spend more time...

**Comment by DashRiprock** [comment]
Thanks for your help.
