### ISSUE TITLE
Grunt warning with uppercase

### ISSUE THREAD

**Issue by Naimikan** [ghiscoding/angular-validation#107]
When I run grunt, throws me the following warning:

> A constructor name Should start with an uppercase letter.

In the line where I do:

`if (new validationService().checkFormValidity($scope.formRegister)) { // ... }`

I think if _validationService_ is a class should be capitalize

**Comment by ghiscoding** [comment]
Unfortunately it's a bad decision that I have to stick with. I can't just come and change it since I would make a 140+ users pissed at me if all of a sudden 1 of the very often used Service is change. 

This typo would break a lot of people's code and I surely don't want that. I realized that I made a mistake long time ago but it's just too late in the game to fix it.

Thanks anyway

**Comment by ghiscoding** [comment]
Finally decided to bite the bullet and fix it under a major 1.5.x branch
See [Revision 1.5.0](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.0)
