### ISSUE TITLE
Predefined Validation Rule For Phone Numbers.

### ISSUE THREAD

**Issue by imanghafoori1** [ghiscoding/angular-validation#111]
The "phone number" validation rule is missing.
(The same is true for "credit card number")

I found these rules present in the jquery validation plug-in:
(additional-methods.js)
http://jqueryvalidation.org/documentation/

**Comment by ghiscoding** [comment]
The credit card validation is there with the name `credit_card`, the phone number is not since it varies a lot for each country. 

If you want to add them, or modify existing one, then please go ahead and submit a pull request. I would accept all the help. It shouldn't be too hard to add, just look a the file [validation-rules.js](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-rules.js) then copy+paste another rule and finally change the `pattern` property then you should be good to go. 

If you make a PR for the phone, please name it so that it represent the country or region (US & Canada do share the same format, so perhaps name it `phone_nam` (for North America).

**Comment by ghiscoding** [comment]
Are you going to submit a pull request and help the community? I would be glad if you do...

**Comment by imanghafoori1** [comment]
I am not that much expert in angular.
I do not know how to do so.
Unfotunatly
در تاریخ ۸ مارس ۲۰۱۶ ۳:۰۶ قبل‌ازظهر، "Ghislain B." <notifications@github.com>
نوشت:

**Comment by ghiscoding** [comment]
Added US phone number rule & tweaked credit card rule, now available in [Revision 1.5.1](https://github.com/ghiscoding/angular-validation/releases/tag/v1.5.1)

Helping the community is a great thing for everyone :)
Take a look at [How to make a GitHub pull request](https://help.github.com/articles/using-pull-requests/), this might help you in the future.
