### ISSUE TITLE
problem validation form in directive

### ISSUE THREAD

**Issue by zaideygrek** [ghiscoding/angular-validation#112]
Hello ghiscoding

And again thank you for your plugin, it helps me everyday!

I have a problem when I have against forms that must be shared. So I use a directive but I have a validation issue. Do you have a tip ?
I created an example plunker (plus the directive in a form modal) (http://plnkr.co/edit/9RkzZtrdmMuLYmKoDKSu?p=preview)
- Validation of the form in the modal working properly.
- By cons the sequence : I click open modal , I click send , I close the modal and I type one character in the text field of the page and I click send gives me an error and without label indicates that the form is validated.

Thanks for you help

Alex

**Comment by ghiscoding** [comment]
Hmm I haven't played that much with validation inside dynamic template. You have many factors that could influence this odd behavior. I think the main problem here is your Form and your Input are always same names. Angular-Validation really uses a lot the Form and Input names to do the validation in the background, you should try to somehow have these names be different so that they don't collide. Because if you look carefully, if you make the 1st input as bad (enter only 1 char in parent window), then you open the modal window and you type something else, you will see that the parent window actually gets the behavior (instead of the modal window). So try changing your names between the parent the modal window, that will probably fix your problem.

Bonne chance

**Comment by ghiscoding** [comment]
Actually that might be hard to do since Template are only read once and then it comes from the cache. Dynamic template is feasible but a little harder. Nevertheless, the problem still relies in the fact that you use multiple input with the exact same name. In your case you have 2 inputs with this `<input name="myInput".../>` and Angular-Validation will validate the first one it finds.

**Comment by ghiscoding** [comment]
I think that I got it working by making the input name dynamic, I use a generic date timestamp to make it dynamic and random so that they none of the input have the same name.

If you had a timestamp in your controller scope and make it available to your directive. You can then make your input like this `<input name="myInput{{timestamp}}" .../>` and it works, there's no more conflict or collision, they are totally separate from each other...bingo :)

Please close this issue if it fixes your problem.

For more code explanation:

Controller
```javascript
myApp.controller('ModalInstanceCtrl', ['$scope', '$uibModalInstance', 'items', 'ValidationService', function ($scope, $uibModalInstance, items, ValidationService) {

  $scope.items = items;
  $scope.timestamp = new Date().getTime();
 // ....
```

html
```html
<my-form items='items' timestamp='timestamp' form-name='test'></my-form>
```

Your directive
```javascript
myApp.directive('myForm', ['ValidationService', function(ValidationService) {
    return {
        restrict: 'EA',
        scope: {
          items: '=',
          timestamp: '='
        },
        template: '<form name="myForm" novalidate="">' +
            '<label class="control-label">test</label>' +
            '<div class="controls">' +
            '<input type="text" class="input-xlarge" name="myInput{{timestamp}}" ng-model="name" validation="min_len:6|pattern=/^[0-9 +]+$/:alt=Votre téléphone nest pas valide.|required:alt=Le champ est requis.">' +
            '</div>' +
            '<button ng-click="send()">send</button>' +
            '</form>' +
            '<br/>Timestamp: {{timestamp}}',
        link: function(scope, element, attrs) {
          scope.send = (function() {
            if (!(new ValidationService().checkFormValidity(scope))) {
              console.log('invalid form');
              return;
            }
            console.log('valid form', scope.items);
          });
        }
    }
}]);
```

Please close this issue if it fixes your problem.

**Comment by zaideygrek** [comment]
Yes thank you I did something like that, I would answer you.
By cons I needed to put in 

validation.directive.js
```javascript
link: function(scope, elm, attrs, ctrl) {
  $timeout(function() {
    ...
   });
} // link()
```

My directive

```javascript
myApp.directive('myForm', ['ValidationService', function(ValidationService) {
    return {
        restrict: 'EA',
        scope: {
          items: '='
        },
        template: '<form name="{{formName}}" novalidate="">' +
            '<label class="control-label">test</label>' +
            '<div class="controls">' +
            '<input type="text" class="input-xlarge" name="{{formName}}_myInput" ng-model="name" validation="min_len:6|pattern=/^[0-9 +]+$/:alt=Votre téléphone nest pas valide.|required:alt=Le champ est requis.">' +
            '</div>' +
            '<button ng-click="send()">send</button>' +
            '</form>',
        link: function(scope, element, attrs) {
          // action 
          scope.send = (function() {
            if (!(new ValidationService().checkFormValidity(scope))) {
              console.log('invalid form');
              return;
            }
            console.log('valid form', scope.items);
          });
          // init
          scope.formName = new Date().getTime();
        }
    }
}]);
```

Thanks a lot !

**Comment by ghiscoding** [comment]
Since it seems to be resolved, I will close this issue then
