### ISSUE TITLE
Control marked invalid when it isn't

### ISSUE THREAD

**Issue by jmichaud-ips** [ghiscoding/angular-validation#113]
I have added ng-class to my parent element for has-error.  When typing in a field with just validation="required", it flashes red, then goes blue again.  This tells me something is marking the control invalid right away, then re-validating after the debounce timer.  Below are two entries.  The first one flashes red, the second one does not, which isn't using angular-validation.  Just ng-model validation and the required field.

`        <div class="form-group" ng-class="{ 'has-error': form1.invalidFlash.$invalid }">
            <label for="invalidFlash">Invalid Flash</label>
            <input type="text" class="form-control" name="invalidFlash" placeholder="text required" ng-model="invalidFlash" debounce="500" validation="required" />
        </div>
        <div class="form-group" ng-class="{ 'has-error': form1.noFlash.$invalid }">
            <label for="noFlash">Invalid Flash</label>
            <input type="text" class="form-control" name="noFlash" placeholder="text required" ng-model="noFlash" required />
        </div>`

I made a plunker example, not sure if its public or not: http://plnkr.co/edit/Iy6saQ9uAmuWdBRanzbi?p=preview

**Comment by jmichaud-ips** [comment]
I tried debounce=0 on plunker and no more blinking, however I still have the quick flash on my website when I set to 0.  Using Chrome for both.

**Comment by ghiscoding** [comment]
Sorry I'm on vacations so I'm late for reply.

Why are you using `ngClass`? There is no reason for using it, `Angular-Validation` will take care of the CSS styling by itself in a correct way and you won't see the colors changing. While on the other hand, using `ngClass` is totally different, I believe that it has to be interpreted every single time with the validation which is why you see the color changing. 

Please don't use the `ngClass`, just modify the CSS as it is shown in this [Wiki - CSS Styling](https://github.com/ghiscoding/angular-validation/wiki/CSS-Styling)

I don't think that I can do anything for your problem, except that you should use CSS styling as I mentioned. I'm thinking about closing this issue unless you have big reason not to.

**Comment by jmichaud-ips** [comment]
You can close the issue.  I was using ngClass because I liked the built in functionality I got with has-error.  I have since reverted to your default behavior of a blue box shadow when the control has focus, and I have applied your recommended CSS styling.  Thanks for the update, and the nice directive.

**Comment by ghiscoding** [comment]
Great thanks for the feedback
