### ISSUE TITLE
validation on blur not work

### ISSUE THREAD

**Issue by cve** [ghiscoding/angular-validation#12]
In the demo, if I focus on the first input and then left them empty (with skip to the next one) the validation not fires, it is possible to show error message on blur?

**Comment by ghiscoding** [comment]
I was previously using the `$dirty` check and saw that they added the `$touched` check for forms in AngularJS 1.3+. This will do exactly what you wanted... Please let me know if it works.

Please note that I made the change through Github webpage since I am in the process of pushing a huge update and don't want to interfere with my current code change... If you want a heads up on what's coming, I am adding Service functionality as well (so we'll have both Directive & Service functionality). I am hoping to have it done by the coming weekend.

Thanks

**Comment by cve** [comment]
Thank you so much :)

**Comment by juanchavezlive** [comment]
Hi @ghiscoding. I have checked most of the existing directives for validation and i think yours is one of the best or even the best. I'm curious about the huge update you will done... will this change be compatible with the current version & implementation ? I look forward to hear from you. Best regards.

**Comment by ghiscoding** [comment]
Hello @juanchavezlive thank you for your support, I actually the big update last weekend which was the date I wanted to push it (I rewrote and separated all my code to support Directive & Service).

But actually 2 min. ago, I pushed another big update, this one for adding full Date Validators (between/min/max). Looks like I have all functionalities that I wanted, so I'm quite finish, I have all the Validators I wanted and it now support both Directive and Service which was asked for by other users... so nothing left to be done I guess... :)

I might be mistaken but, is your name latino? It would be really nice to also have Spanish translation... I would really like to have help and see a Pull Request adding this language (or any other language).

Thanks for your support and spread the word about my code :)

**Comment by juanchavezlive** [comment]
Thanks a lot for you prompt response @ghiscoding. I continue evaluating your project and looks very interesting, however i have 2 doubts:
1) How can i show all the validation errors when the users press the submit button?
2) Why your project is not registered in bower ? 

Regarding the translations... i will do it for Spanish & Portuguese. Just give me to the weekend to complete them ;)

**Comment by ghiscoding** [comment]
Hello @juanchavezlive, 
1) I don't have this feature since I took a different approach, instead of having the submit button enabled at all time, I actually disable the submit until the form becomes all valid (most form validation example that I have seen do it this way) with `ng-disabled="form1.$invalid"`... Nonetheless, having a list of errors would require code change, which might be doable in the future.
2) Not registered in Bower, I do this project on my free time and haven't yet looked into publishing it elsewhere than Github. 

You are asking for 2 valid points though I don't have answer, neither an implementation of this kind at the current moment. As I said, I do this on my free time and still have other things to do, I would really love to have some help. The enhancement that you are asking are most probably doable but I can't promess you of any given date for them to be available.

Please Note:
Could you please open an issue and I would then label it as an "Enhancement" request, I would prefer to stop writing on this issue here since it is in a "Closed" status and we are deviating from the original question asked by the other user. I would prefer to see an "Open" issue.

Thank you

**Comment by ghiscoding** [comment]
Hello @juanchavezlive. I started looking at both and I might have something ready by the weekend. Again please open a new "Issues" so I can have better tracking... I will wait for you to create one before pushing my new code.

Thank you

**Comment by juanchavezlive** [comment]
Hello @ghiscoding. I will do it tomorrow my friend. Additional to this I will have ready the translations before the weekend ;)
