### ISSUE TITLE
Support in Angular 2?

### ISSUE THREAD

**Issue by joshgarwood** [ghiscoding/angular-validation#122]
Hi there!

I am currently building a new app in Angular 2 (via ionic2) and was wondering if there are any plans to release an Angular 2 version of this validation framework.  I can't believe that Google didn't implement something like this already, because their base validation framework is terribly verbose and complicated.  

Thanks, and I hope all is well!

**Comment by ghiscoding** [comment]
I totally agree with you... why didn't AngularJS implement a better validation package? But hey, that's why I made my package..right!

Unfortunately though, I have no plan for AngularJS 2.0 rewrite. I am moving on and away from AngularJS, I am leaning towards using [Aurelia](http://aurelia.io/) as my next framework of choice. 

If someone else however wants to fork my code and make it Angular 2.0 then please do so. But at this point, there isn't any plans for a 2.0 version...  best of luck and thanks for using the package ;)

**Comment by ghiscoding** [comment]
Oh thanks Johnny, 

I am looking into Aurelia mainly because I don't like at all the new syntax which is ugly and meaningless. Also, Aurelia is meaningful and requires a lot less code, they also follow the standard while Angular isn't. 

I'm not saying that I won't ever do an Angular 2 package of `Angular-Validation`, but I think that if I ever do, it might take a while (probably months). I spent a lot of time on this package and I would rather spend time on something else, so this package is very low priority for me.

**Comment by jdriesen** [comment]
Thanks for taking your time to write this valuable reply, Ghislain.
And yes, you're right about 'Angular not following the standards'.

On the other hand... the Angular community is bigger compared to the Aurelia one, so getting support via fora is maybe a bit more easy ...

As a conclusion... personally, I don't know yet which FW to choose...

Grtz,
Johnny

**Comment by noherczeg** [comment]
@ghiscoding What is your experience with Aurelia so far? :)

**Comment by ghiscoding** [comment]
@noherczeg I like Aurelia in general, you can see the other repos which are under my [name](https://github.com/ghiscoding), I got more Aurelia than AngularJS now. The only downside is that it has less traction in the community compare to Angular and so, Releases and Support then to be a bit slower to get, but for the rest I love Aurelia syntax and simplicity compare to Angular. 

On the Angular side, I am not planning on rebuilding `Angular-Validation` anytime soon, and from what I heard the validation will be simpler in Angular 5. To be fair, I haven't started working with Angular 2+ yet, though I will in the coming months. Thanks

**Comment by noherczeg** [comment]
My biggest problem right now is that I'd like to trash our in-house validators, but we rely heavily on getterSetters and we also use kendo components as well in a context where our forms are dynamically generated.

This lib was promising, but I guess due to our situation it's way more problematic than what this has been prepared for :)

I'll check out your repos for sure though!

**Comment by ghiscoding** [comment]
Considering that Angular has better validation process and also Reactive Forms (which we use in our teams), this lib won't be rewritten for Angular 2+ and so I tag this issue as "won't fix"
