### ISSUE TITLE
Get validation result without html elements

### ISSUE THREAD

**Issue by radman0x** [ghiscoding/angular-validation#143]
Hi,

Just wondering if it's possible to get the result of validation without having to create html input fields? Is there some part of the library that can be used to validate using the text patterns but feeding data directly rather than binding to an input field. 

The situation I have is that there are multiple pages of fields that the user can enter values for, once a value has been entered it is stored. Upon navigating to a new page the <input> fields on the old page no longer exist but I need to retain whether or not the values entered into the fields were valid. If not valid then the user shouldn't be able to submit. 

Any suggestions?

**Comment by ghiscoding** [comment]
Hmm that's a bit tricky, however there might be some ways to do it. You probably have a "Next Page" or something, if that's the case then make a copy of the [Wiki - $validationSummary](https://github.com/ghiscoding/angular-validation/wiki/Validation-Summary), or actually I would probably not permit to change page if the first page is not valid. You could maybe also try to set [Wiki - resetGlobalOptionsOnRouteChange: false - from the Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options). Good luck

**Comment by radman0x** [comment]
Thanks for the quick reply.

The concept that is being pursued is multiple pages with input fields and as the input fields are modified a global changelist is built up of the changes and this is maintained irrespective of the navigation between pages. So a user could go to one page, make bad inputs, navigate elsewhere and then come back later to fix the issues. 

I've been looking at if I can use the ``function validate(strValue, showError) {`` from ``validation-common.js`` with a dummy object or similar to avoid having to have actual input tags, is there any possibility in this approach?

**Comment by ghiscoding** [comment]
Well it wasn't design for that, anything that is in the `validation-common.js` file is a common place that holds functions for both the Directive and Service. However, nothing blocks you from trying, you can give it a try but I won't give you much support on that though. I have other projects that I'm working on.

**Comment by radman0x** [comment]
Thanks for the follow up answers. Just thought I'd put here that I won't be working on this for a while but that I will report back once I do get around to it.

**Comment by shouhengli** [comment]
Hi @ghiscoding , thanks for replying to this issue. Just let you and anyone who follows this issue know, because @radman0x was busy with some other work, I took this over from him. We finally came up with an acceptable solution and hence the ticket can be closed.

**Solution**
Wrap each input field into a `ng-form` and keep a list of each form's `formController`. A form controller has a `$valid` property which is later combined to check a page's validity, e.g.if one of a page's formController has a falsy `$valid`, the whole page is considered invalid.

This is also based on the assumption that when a page is no longer displayed, its validation status of the underlying data won't change unless it is displayed again. For example, a user made changes that invalidates the current view and navigate away, the page will remain invalid unless the user navigates back later and make changes again.

**Con:**
The solution requires each page's validity to be saved and tracked, which adds complexity for future development, e.g. adding route/view will require adding validity/form controllers in validation checker too.

**Comment by ghiscoding** [comment]
have you tried using `$scope.$validationSummary`? This also technically holds all the invalid inputs (only the invalid ones), you can combine that just like you did without the need for `ngForm` I believe.

**Comment by shouhengli** [comment]
I did play with `$validationSummary` a bit but it doesn't seem to be as reliable as `$valid` for some reasons. Also we call `ValidationService.checkFormValidity` explicitly, which requires `ngForm` anyway. I did use `$validationSummary` to gather validation message btw

**Comment by ghiscoding** [comment]
Ok so I will close the issue, even though as you said this is not ideal but working. Thanks for the update and feedback
