### ISSUE TITLE
custom directive validation

### ISSUE THREAD

**Issue by shomid** [ghiscoding/angular-validation#146]
I created a custom directive and set validation.
my code in following :
`"use strict";`
`var demo = angular.module("demo", [ "ghiscoding.validation" ]);`

`demo.config([ '$translateProvider', function($translateProvider) {`
`    $translateProvider.useStaticFilesLoader({`
`	files : [ {`
`	    prefix : 'validation/locale-',`
`	    suffix : '.json'`
`	} ]`
`    });`

`    $translateProvider.preferredLanguage('fa');// is applied on first load`
`} ]);`

`demo.controller('demoController', function() {`

`})`

`demo.directive('myInput', function() {`
`    return {`
`	restrict : 'E',`
`	require : "ngModel",`
`	scope : {`
`	    ngModel : '='`
`	},`
`	template : '<input type="text" ng-model="ngModel" />',`
`	link : function(scope, element, attrs) {`

`	}`
`    }`
`});`

my index html code :

`<!DOCTYPE html>`
`<html ng-app="demo">`
`<head>`
`<meta charset="UTF-8">`
`<title>Insert title here</title>`
`</head>`
`<body ng-controller="demoController">`

`	<form name="frm">`
`		<my-input ng-model="demoText" name="demoInput" validation="required" validation-error-to="spanError"></my-input>`
`		<span id="spanError"></span>`
`		<input ng-model="demoText" name="demoInput" validation="required" validation-error-to="spanError1">`
`		<span id="spanError1"></span>`
	
`		<button type="submit" ng-disabled="frm.$invalid">submit</button>`
`	</form>`

`</body>`
`<script type="text/javascript" src="bower_components/angular/angular.js"></script>`
`<script type="text/javascript" src="bower_components/angular-translate/angular-translate.min.js"></script>`
`<script type="text/javascript" src="bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js"></script>`
`<script type="text/javascript" src="bower_components/angular-validation-ghiscoding/dist/angular-validation.min.js"></script>`
`<script type="text/javascript" src="js/app.js"></script>`

`</html>`

but user focus in custom directive and unfocus with empty value, validation not show any mesage.
but user focus in input tag and unfocus with empty value,validation show message .

**Comment by ghiscoding** [comment]
You should really clean up your comment, it's totally not readable. 

If your problem is actually what is written in the last sentence, then I can say that `Angular-Validation` by default does not show the error right away to the user (it's a personal taste, as I don't like bothering the user with errors when he didn't even start typing anything). As for the input tag, that is a 3rd party directive that I don't fully control, I can validate it but I can't totally have the same behavior as regular inputs. 

I don't see your last sentences as an issue, so I'm closing it. If you want help in the future please use [Plunker](http://plnkr.co/) or try escaping your code properly in the comments

**Comment by shomid** [comment]
[http://plnkr.co/edit/Sr7NZIcjf13p9EEZe3PL?p=preview](http://plnkr.co/edit/Sr7NZIcjf13p9EEZe3PL?p=preview)

when user focus in custom directive(first element in example) and blur without empty value, validation not show any error message.
but user focus in input tag(second element in example) and unfocus with empty value,validation show error message .

why validation not show error message for my custom directive ?
