### ISSUE TITLE
Remote validation does not work when wrapped in a custom directive

### ISSUE THREAD

**Issue by mgm09a** [ghiscoding/angular-validation#148]
Hello,

Firstly, thank you for this wonderful plugin! It has truly been very helpful!

We have a custom directive that wraps your plugin so we don't need to repeat the implementation details on every page and Angular controller. The problem is that we are trying to use your remote validation feature to validate that a certain value is valid before the user clicks save, but it's not working from within our directive. The validation call seems to be called multiple times from different scopes, and only one of them has access to the remote validation function.

I have replicated the issue in [this Plunker](https://plnkr.co/edit/CWnzB2rNZ3tLI5iUh4YV?p=preview). See the console to see the errors we're encountering.

Please, if you have some time, could you help me figure out if we're misusing your plugin or if there's something else that's the cause of this?

**Comment by ghiscoding** [comment]
You might have to use [Wiki - isolatedScope](https://github.com/ghiscoding/angular-validation/wiki/Isolated-Scope) for that to work. 

Not sure where the error comes from but you could troubleshoot with the unminified code, that would help finding what is throwing the error. So if I replace the call to `Angular-Validation` with the following unminified code.
```javascript
<!-- angular-validation -->
<script type="text/javascript" src="https://rawgit.com/ghiscoding/angular-validation/master/src/validation-directive.js"></script>
<script type="text/javascript" src="https://rawgit.com/ghiscoding/angular-validation/master/src/validation-service.js"></script>
<script type="text/javascript" src="https://rawgit.com/ghiscoding/angular-validation/master/src/validation-common.js"></script>
<script type="text/javascript" src="https://rawgit.com/ghiscoding/angular-validation/master/src/validation-rules.js"></script>
```

After doing that, I can see that your `Promise` seems invalid, since it throws an error on line 1338 of `validation-common.js` file. The line of code is this:
```javascript
if (typeof previousPromise.abort === "function") {
    previousPromise.abort(); // run the abort if user declared it
}
```
In my code, I forgot to check that the `Promise` isn't `undefined` (funny enough, I did that check on line 1345 but forgot line 1338). However that won't fix your problem, but at least you know what throws the error.
```javascript
if (!!previousPromise && typeof previousPromise.abort === "function") {
    previousPromise.abort(); // run the abort if user declared it
}
```

I think that `Angular-Validation` tries to find the function and the Promise in the current scope but fails to do so. I can correct the missing `undefined` try-catch, but you still have to fix your issue. I believe that for this to work, you have to find the way to pass the scope of the parent to the directive, or at least the scope that contains the remote function should be the same scope called by the validation.

**Comment by mgm09a** [comment]
I appreciate you taking the time to look into this issue.

I made that change you mentioned (checking for an `undefined` `Promise`) locally until the source code is changed. I have been trying all day to utilize the isolated scope you mention, but I still end up getting the same "Remote Validation requires a declared function (in your Controller) which also needs to return a Promise, please review your code" error.

I'm pretty sure it's just a scoping issue, but I don't know where/how to ensure that your call to validate always has access to the proper scope. Do you have any additional suggestions?

Again, thank you very much.

**Comment by ghiscoding** [comment]
Ok, I don't want to push any new revision with such a small code change (and that doesn't bring any good to the table anyway). 

As for the scoping issue, I do believe that is the issue. Using `isolatedScope` is a way to make sure that `Angular-Validation` uses the same scope for everything, that is helping doing validation in Modal window for example. Looking at the code, I can guide you to do some troubleshooting, but I would rather not do it myself if possible. Here's first thing you can check, put a breakpoint on line 1332 which is this line of code `var promise = runEvalScopeFunction(self, fname);`, I would expect the `self`, that is `self.scope`, (but I bet that it's not) to hold the same scope as your parent scope (hopefully also the same scope as where you defined your remote function). The function `runEvalScopeFunction()` does an `$eval` to transform a simple string into a javascript object/function depending on what it finds and in your case that function probably returns `null` because it didn't find it. Start with that and give me the result then we'll go further.

**Comment by mgm09a** [comment]
So I've added the `$scope.$validationOptions { isolatedScope: $scope };` call to our controller, as seen in this [updated Plunker](https://plnkr.co/edit/CWnzB2rNZ3tLI5iUh4YV?p=preview). The call to `runEvalScopeFunction(self, fname);` is now being consistently called from our custom directive scope (though it's still being called twice, which is not ideal because this validation fires AJAX calls to our server).

The `$validationSummary` and call to `checkFormValidity()` are now not working though.


We have decided to not worry about getting client-side AJAX validation for this particular field to work and simply provide our server side validation.

Thank you for your time and help--you may close this issue.
