### ISSUE TITLE
May I manually "reload" validation directive?

### ISSUE THREAD

**Issue by kuanyen** [ghiscoding/angular-validation#149]
Thanks for your great Angular plugin.

I found when a form is under `ng-show`, the `validation` message in it will become invisible. e.g:

```jade
div(ng-show="currentIndex===0")
  form(name="ipForm0")
    input(type="text" validation="ip|required")
div(ng-show="currentIndex===1")
  form(name="ipForm1")
    input(type="text" validation="ip|required")
```

If `currentIndex` is initialized to 0, then the validation message in `ipForm1` will not show at all(but `ipForm1.$invalid` still works.)

If replace `ng-show` with `ng-if`, this problem is even worse: `ipForm0.$invalid` and `ipForm1.$invalid` will become disability.

Any way to manually "reload" validation directive to solve this problem? Or is there any better solution for this situation? Thanks.

**Comment by ghiscoding** [comment]
You should take a look at the [more-examples/ngIfShowHideDisabled](https://github.com/ghiscoding/angular-validation/tree/master/more-examples/ngIfShowHideDisabled) folder for an example with `ngShow` and `ngIf`. As it is written in that example, you should probably use `ngDisabled` when `ngShow` is in an hidden state. The main reason is that `Angular-Validation` doesn't validate a `disabled` element.  As for the `ngIf`, it shouldn't display anything since `ngIf` doesn't create any DOM elements. 

Something else to know, `Angular-Validation` doesn't display any errors on first page load (because that is the default I chose), but if you do want to see them right away, you could look at the [Wiki - GlobalOptions](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) with the option of `preValidateFormElements: true`.

**Comment by kuanyen** [comment]
Thanks for your quick reply.

Hmm, I found I cannot reproduce the problem I encountered. The same code (from example file) in my production code does just not work.

So I made a dirty (but works) directive to do this: insert message element + ng-show in the beginning, instead of dynamically inserting.

**Comment by IS-Kuan** [comment]
Now I use `ng-include` to wrap the form needed to be validated, now seems no problem.
