### ISSUE TITLE
Validation does not work correctly if forms are dynamically changed on page

### ISSUE THREAD

**Issue by CoolDadTx** [ghiscoding/angular-validation#156]
We have a scenario where we have Add/Edit/Delete options on a page. The Add and Edit options use forms. The first add/edit works correctly but validation no longer works after the first submit. For Delete JS errors occur because a form is no longer present. The page shows a list of items and, because of how the UI is laid out, we have a single Add form and 1 Edit form for each item in our list.

For the Add scenario it validates correctly and posts back to the server. Because a single change can impact multiple elements we reload the array of items on the JS side. Once we do that the Edit validators no longer work. Looking into the code, the validator for an input is correctly detecting the error but it isn't hooking up to the validationSummary to report it. The data all seems correct.

For the Delete scenario we refresh the array of items again (because of dependencies). Then we get errors in the console because validation can no longer find form elements that used to exist.

I'm trying to figure out how to work around this scenario. My first thought was to create a single Add and Edit form and then dynamically position it where it needs to go in the UI based upon the user's action. This ensures the forms are always available. It isn't elegant but it seems like it'd work.

The preferred approach would be to refresh the data and then call something in the validation to cause it to basically rebind to the new data. I can see where we can unbind all the existing validators but I don't see a way to trigger binding again. Is there any way to do this?

**Comment by ghiscoding** [comment]
Are you doing routes redirect by any chance? If so, you should look at the [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) and disabled `resetGlobalOptionsOnRouteChange: false` so that the validations don't reset on a route change.

You can trigger a revalidate by calling : 
See [Wiki - Revalidate Input](https://github.com/ghiscoding/angular-validation/wiki/Revalidate-Input)
```javascript
// where elementName is the input name="elementName"
// you might need to wrap it inside a `$timeout`
$scope.$broadcast('angularValidation.revalidate', elementName);
```

**Comment by CoolDadTx** [comment]
No I'm not doing any routing. I make an AJAX call to the server. It sends me an updated list of items. The existing JS array is replaced with the new array. The HTML has a form rendered for each item. Since all the existing forms are removed from the DOM when the new array is loaded I lose all the validation (although it still validates them). 

Using the broadcast doesn't seem like it'll help. The issue is that: a) I don't know the names of the elements as it is an arbitrary list, and b) revalidation assumes that the validators are properly hooked up and they don't appear to be. Furthermore deleting an element periodically causes a JS error because it appears the form disappears and the validation library doesn't realize it.

I have given up trying to get the validation library working with dynamic forms. It doesn't seem to be a case that it is designed for. I've switched to having the forms outside the normal HTML and "swapped" in during editing. This seems to make the validation happy and doesn't require too much code.

**Comment by ghiscoding** [comment]
You might want to take a look at the various samples in the project folder [more-examples](https://github.com/ghiscoding/angular-validation/tree/master/more-examples), especially the [dynamic form example](https://github.com/ghiscoding/angular-validation/tree/master/more-examples/dynamic-form). These were all examples that were created because of validation issues that were brought up by some users.

It's a little hard to help you more than that without a Plunker to test against.

**Comment by ghiscoding** [comment]
Since no Plunker code sample was provided, I cannot help you with this. 
I decided to close the issue because of no feedback and Plunker provided.
