### ISSUE TITLE
Email Validation fails esoteric use cases

### ISSUE THREAD

**Issue by sonicdivx** [ghiscoding/angular-validation#161]
Reviewing Email validation libraries and test various valid emails found here

https://en.wikipedia.org/wiki/Email_address#Local-part

and many of the valid use cases fail to validate correctly. Realize these are edge cases and I certainly would not want to handle  **"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com**
It is valid.

FYI many validators fail that test.

**Comment by ghiscoding** [comment]
I have already passed way too much time on these edge cases (for example issue #45), and since then it does already support a lot of these cases. If you think the [Regex validation rule](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-rules.js#L561) can be tweaked then please go ahead and make my day, but I won't personally pass more time on this. There's a limit of what you can do with a Regex too

**Comment by ghiscoding** [comment]
cleaning and closing older issues, I won't do this change
