### ISSUE TITLE
Conditional required validation

### ISSUE THREAD

**Issue by yupswing** [ghiscoding/angular-validation#165]
Hello @ghiscoding ,
I am trying to make a custom remote validator.

In a very particular case I have to make a field required based on a remote condition and if other fields are filled or not.
I made a custom remote validator but it does get triggered ONLY if there is some value in the field (not when it's empty).

Is there a way to make a conditional required validator?
I can't find anything in the wiki.

Thanks.

**Comment by ghiscoding** [comment]
Perhaps [Wiki - Validate on Empty](https://github.com/ghiscoding/angular-validation/wiki/Inputs-(local-options)#validate-on-empty)

**Comment by yupswing** [comment]
yeah, that's exactly what I was looking for, but...

if I use `required` and I don't touch the form when I submit 
`new ValidationService().checkFormValidity()`
it returns **false**.

but if I use `validate-on-empty="true"` it does pass validation successfully when field IS empty and my remote validator is just (in theory always failing)
`return $q.when({isValid: false, message: 'test error'});`

Maybe I did not understand, or `validate-on-empty` attr has a slightly different behaviour (on trigger matter) than `required` validator

(thanks for your answer, you are always very responsive and I honestly appreciate that a lot)

**Comment by ghiscoding** [comment]
I recently made a change #160 that might affect the usage of the `validate-on-empty`. The big problem that I have is that my E2E tests are broken since new versions of Chrome/Protractor and my last attempt to fix them was not really good. I don't have time to look into fixing the E2E. 

If you could take a look at his [Plunker](http://plnkr.co/edit/eWyQngo8j3ffqP0MqcGl) (from #160) and try to reproduce your behavior in there, that might help to find the real issue.
