### ISSUE TITLE
Having problems with live disabling the "Save" button

### ISSUE THREAD

**Issue by sumcoding** [ghiscoding/angular-validation#173]
https://github.com/ghiscoding/angular-validation/blob/2da692349ffaffca5b66ef7708659f281aa47741/dist/angular-validation.js#L189#L190#L191#L192

I am using formName.$invalid to disable and enable my button. 
The above chunk of code is causing the button to flash from enabled to disabled as I type in the input which is set to validation="required" (my updateOn is set to keyup as this is what I need). Is there any reason this is needed? If I remove it my problems are solved.

**Comment by ghiscoding** [comment]
To invalidate the field is mostly as a "catch all", it's better to invalidate the field before doing any validation. It's especially especially used with fields that have asynchronous validations (a validation that resolves in later in time). I cannot remove this line as it will for sure break people's code and cause more issues. 

But why is it flashing in your case? You removed the debounce delay (default to 1.5sec)?

**Comment by sumcoding** [comment]
Makes sense I suppose.
When you say removed debounce, what do you mean?
I have set it to 0, but it does not seem to matter what my debounce is set too (using the debounce="" not the global setting btw), since it always immediately invalidates the input and only uses the debounce to then validate it again.

**Comment by ghiscoding** [comment]
I mean the default behavior of Angular-Validation is to use a debounce of 1500ms, that is set in the [Global Options](http://www.codingdrama.com/bootstrap-markdown/) or through the element itself via the [Directive](https://github.com/ghiscoding/angular-validation/wiki/Working-Directive-Examples). 

What I mean is that you see it blinking because you probably set the debounce to 0, if you set it to higher number, you probably won't see this blinking behavior because it will remain invalid until you finish typing and then validate at that time.

**Comment by sumcoding** [comment]
Apologies for the delay, holidays.

A higher number just means longer flashes for me. The problem is that it does not debounce when it invalidates the form, and it also doesn't check if the input is empty. So every time I type it will set the form to invalid when I finish my final keyup (despite it not actually being invalid since its only requirement is that its not empty), making the button look disabled for however long the debounce is set too and then enable the button again when it revalidates the form. 

Doing a check to see if it is empty before invalidating the form fixes it, but not sure if that would break its catch all use or the asynchronous validations. 

```
 // invalidate field before doing any validation
          if(!!value && (value === "" || value === null || typeof value === "undefined") || commonObj.isFieldRequired() && (value === "" || value === null || typeof value === "undefined") || _validateOnEmpty) {
            ctrl.$setValidity('validation', false);
          }
```

**Comment by ghiscoding** [comment]
I would rather not change the code anymore, since over a year my Protractor tests are broken because of earlier version of Protractor and so without relying on my E2E tests. The lib is loaded with features and options, perhaps there's something we're missing, however I'm using it less myself (my work moved to `Angular 4/5` which I personally dislike but that's another topic).

So without any working tests on my side, I would rather not change my code.

**Comment by sumcoding** [comment]
Understandable. 
Thanks for taking the time to respond,

Cheers!

**Comment by ghiscoding** [comment]
cleaning up and closing older issues
