### ISSUE TITLE
Incorrect validation on "required" with a value of 0

### ISSUE THREAD

**Issue by mgm09a** [ghiscoding/angular-validation#177]
I understand this project is just on life support, and I know that you've mostly moved on to working with other technologies, but I wanted to ask if this odd behavior was by design before I attempted to investigate much further.

http://plnkr.co/edit/t2zzENCdQp163F4IsZH3?p=preview

In this Plunker, you'll find an example of some odd behavior. On my `ng-model`, the value is initialized to `0`. The `select` element to which it is bound is decorated with `validation="required"`, but the classes that initially get assigned to that element indicate that it is invalid.

I would have expected that a value of `0` would have satisfied the `validation="required"` rule, but perhaps that was a mistaken assumption.

More interestingly, if I change the selection to another value, then *back to `0`*, the `required` validation passes. This makes me think that something is not right, as the behavior changes after the element becomes dirty.

Should this behavior remain the same, or should I look into creating a pull request (my first ever) to try and fix it?

**Comment by ghiscoding** [comment]
Hmm that could be a bug, but yeah I probably won't spend much time on troubleshooting it because as you said it is in "Life support mode" but I certainly accept PR if you find the bug for sure. 

If I look at the code, most of every validation rule are driven by RegEx (which BTW is awesome) and you can see the `required` validator [here](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-rules.js#L780) which basically check for non-empty spaces. 

Quickly looking at the code and searching for the word "required", I can see that I do check for the value to be not empty string, neither undefined or null [here](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-directive.js#L173) but on this other [line](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-directive.js#L182) I checked the value as `!!value` and having `0` won't make it go in the `if`, so on your side you can try to change the code to check the empty string/undefined/null like I mentioned in previous [line](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-directive.js#L182). That's a good troubleshooting start, if it's more than that then I'll let you dig more into it

**Comment by mgm09a** [comment]
I believe I've fixed the issue. The cause is [line 406 in validation-directive.js](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-directive.js#L406).

In the `revalidateAndAttachOnBlur` function, you're finding the value to validate...

    var value = ctrl.$modelValue || '';

...but this causes `0` to be replaced with `''`.

I've updated this line to be:

    var value = ctrl.$modelValue !== null && typeof ctrl.$modelValue !== 'undefined'
                        ? ctrl.$modelValue
                        : '';

and the issue seems to be resolved.

---

Now, as I've mentioned, I've never done a pull request. I'm currently reading about how to do that, so it might be a little while... hahha.

**Comment by ghiscoding** [comment]
@mgm09a 
There's always a first time for everything 😉 

I quickly looked at the PR, it seems fine, I'll review it more in depth tonight and will probably push a new release by then. 

Thanks again 👍

**Comment by ghiscoding** [comment]
closed by merge of PR #178, [NPM](https://www.npmjs.com/package/angular-validation-ghiscoding) is now bumped to version `1.5.26`

@mgm09a 
Thanks a lot for your first ever PR on GitHub, hopefully this will make you contribute to this wonderful Open Source community 😉 🥇 

Cheers 🍺
