### ISSUE TITLE
between_num:1,5 can't validate a zero value when using input type number

### ISSUE THREAD

**Issue by MartinChangCF** [ghiscoding/angular-validation#180]
Hello @ghiscoding ,

I have encounter a problem when using
- `validation="between_num:1,5"` on `input type="number"`.

If passing `0`, I'm expecting a invalid result but seems resulting in a valid response.

Only under circumstances below, I could get the result I need.
- `validation="between_num:1,5|required"` on `input type="number"`

or

- `validation="between_num:1,5"` on `input type="text"`

Wondering why this happens.

Thanks.

**Comment by ghiscoding** [comment]
Hello @MartinChangCF 
I'm sorry but this library is no longer supported, however if you want to troubleshoot and push a fix, I would accept it. Sorry I cannot help you more than that.

**Comment by mgm09a** [comment]
Hi @MartinChangCF,

Take a look at these lines in `src/validation-common.js` (`strValue` is the value of the field's contents):
https://github.com/ghiscoding/angular-validation/blob/3a1c83aac30ccb2f3631c9bf131c63223a82443d/src/validation-common.js#L584-L587

The logic is designed such that if a field is **empty** _and_ **not required**, then it passes. This provides the flexibility to accept an "empty" value (technically, any "falsey" value), while still validating any inputs that are non-empty.

Perhaps a bit unclear, though, is the handling of the special case of the numeric `0`, as you've run into here. If you refer to the snippit above, you see the `!strValue` becomes `true` (because `!0` → `true`) and validation passes. It works when it's a string type, because `!'0'` → `false`.

Without a major breaking change, the simple workaround is to add "required", or you can try [`validate-on-empty="true"`](https://github.com/ghiscoding/angular-validation/wiki/Inputs-(local-options)#validate-on-empty) (though, I'll admit, I haven't used the latter).
