### ISSUE TITLE
Error messages shown on submit are non-understandable as compared to those on blur of field

### ISSUE THREAD

**Issue by p09** [ghiscoding/angular-validation#20]
![erroronblur](https://cloud.githubusercontent.com/assets/11771194/7039654/bdeb028a-dde2-11e4-8062-96fc4b04656b.png)

This is the error message on blur of  the first field field and it is quite understandable as it reflects the error value as would have been mentioned in the locale file

![errorsonsubmit](https://cloud.githubusercontent.com/assets/11771194/7039678/ed3e0848-dde2-11e4-92ae-2e5150e74bea.png)

But here on submit when the errors are shown they do not reflect the locale file value. Does angular-translate fail for erros on submit but works on blur?

**Comment by ghiscoding** [comment]
I still seem to have timing issues with the locale loading, the load seem to happen to late and the errors are not yet translated. The locale translation seems to be loaded asynchronously rather than synchronously, which means that the JSON file is not yet parsed while the errors are displayed. I did lot of adjustments to remove that behavior but still can't get rid of it completely. I would love to have some help on the subject

**Comment by p09** [comment]
You are right. I have run the example on my locale and this issue is not reproduced so its fair enough to say that this won't cause any problem when the code is moved to a server.
Thanks.

**Comment by ghiscoding** [comment]
I now believe that I finally fixed this issue, next code merge will fix this
