### ISSUE TITLE
Option for last validation message and validate when i leave input

### ISSUE THREAD

**Issue by lukasw44** [ghiscoding/angular-validation#33]
Hello 

your validator is nice. Is there any option that allow to show only last invalid message for example now i have got input with validators :'validation="email|required"' and then i have got two errors : 

Must be a valid email address. Field is required.

But cen i show only last message, and after that show another. 

And my other question is is there any option to valid input after leaving field ?

**Comment by ghiscoding** [comment]
Hi,

I'm not sure to fully understand your questions. The way the code is done is that it shows all errors, if user start typing and fixes 1 error then only 1 error will be left displayed. I do not want to change that behavior, sorry.

Leaving an input already does a validate, I use the `$touched`, so whenever you leave the field then the error shows up because it's been touched.

**Comment by ghiscoding** [comment]
Your first request of showing only 1 error at a time was added into the latest [version 1.3.23](https://github.com/ghiscoding/angular-validation/releases/tag/v1.3.23). So you can call it this way:
```javascript
// make sure to inject the `validationService` into your controller
new validationService().setDisplayOnlyLastErrorMsg(true);
```

As for the other request, I already mentioned the following: 
*Leaving an input already does a validate, I use the $touched, so whenever you leave the field then the error shows up because it's been touched.*
