### ISSUE TITLE
Questions / Samples?

### ISSUE THREAD

**Issue by tiwarisnehal** [ghiscoding/angular-validation#50]
Hi there. Thanks for providing this module and thanks in advance also for having a look at my questions. Kindly let me know if any of this is possible/doable and link to some samples if you have any.

1) How to use validationService when using 'Controller as' syntax.
2) I would like to have global configuration at Application level, rather than specify it for each Controller. Is this possible?
3) When using the Directive syntax, can I specify conditional validation. 
    i.e. only apply validation when some condition is satisfied.
4) How do I remove Error message/status when some other field changes.
   e.g. In your specified sample @ http://plnkr.co/edit/jADq7H?p=preview
   say when passwords dont match, error is displayed for confirmation field.
   But when user then changes the first password field so that passwords match, then the error should be removed.
5) While I am using 'Controller as vm' syntax, using remote: for validation for a function defined on 'vm' returning a promise, I get error from angular-validation stating 'vm' is undefined. How do I get around this.

Thanks once again.
- Snehal

**Comment by ghiscoding** [comment]
Wow you have many questions, just to point out, I made this library available to everyone but it's based on my personal time and even though I passed a lot of time in the past, I hope that there will be less time to spend on that library in the future as I eventually want to focus on something else.

To answer some of your questions
1) ControllerAs is coming in next version 1.3.36 which is probably in the coming few hours
2) The global configurations are global as per the controller, as soon as there is a route change, I am resetting all properties of it. I do not want to change this behavior, but I would suggest you to just create an AngularJS config and just reuse it in each controller, that way they all have the same config. Something similar to this
```javascript
var app = angular.module('myApp', [ ]);
app.value('validationConfig', {
    debounce: 1500, 
    displayOnlyLastErrorMsg: false,
    preValidateFormElements: false 
  });

// then inside your controller, just reuse the config
app.controller('MainCtrl', function($scope, validationConfig) {
    $scope.$validationOptions = validationConfig; // use the config set in your app module
});
```

3) Conditional validation, I believe what you are looking is the following [Wiki - Custom Regular Expression Pattern](https://github.com/ghiscoding/angular-validation/wiki/Regular-Expression-Pattern)
4) The only validation that is influenced by another field is as you found out the `match` validator. There is no function to remove 1 error message in particular, removing an error message by the client would go against the concept or the rule of a validation (I mean why validate it, if the client can remove the error anyway?)
5) Again this is the same as #1), it will be a new functionality in the next few hours when I'm done with all my Protractor tests and when I'm done updating the Wiki for it. For a short introduction on this functionality, there will be a new property inside the global config for `controllerAs`

**Comment by tiwarisnehal** [comment]
Hi there and thanks for the quick response.
I understand its a personal endeavor on your part and I very much appreciate you contributing it to the community.
Would have liked to keep this short but could not compress it more. Thanks for your time mate.

1 & 5) I will wait for the next release.
2) Got the tip. I will do something similar.
3) To clarify, While using the directive syntax, what I wanted to do was specify a validation that was to be performed only if a certain condition was met.
    e.g.: fieldX is required only when fieldY has a value > Z.
    i.e. something similar to ng-required.
    I know that I can get this sorted if I use the service syntax and adding/removing the validator when required.
4) I think some functionality on the client to remove error status/validations arises when you have a group of fields to be validated as one.
    Continuing with my example for 3, say if user set fieldY value > Z, then required validation for FieldX should kick in. But when user goes back and changes fieldY value < Z, then the required validation for FieldX should be removed and any error messages on the screen should be removed.
   I know I should be able to do all this using the Service syntax and adding/removing validators as required.

As a new question: 
Q) Can angular-validator be used in combination with in build angular validation? What I noticed is, upon trying to do this, $error was pre-populated upon form load even when preValidateFormElements: false was specified. 
Note: For angular-validation validators, 'preValidateFormElements: false' works as expected, but for native angular validations, it did not work.

e.g.
```
              <input type="password"
                     name="Password1"
                     ng-model="vm.editedRow.password"
                     validation="min_len:2:alt=Minimum Password Length of 6 Required
                                |required:alt=Please re-enter password"
                     validation-error-to="#passwordErrorText"
                     ng-required="vm.action === 'add'">
              <span class="error" ng-show="vm.editForm.Password1.$error.pattern">
                Invalid Entry. Spaces not allowed in Password.
              </span>
```
In this case, the span following input is visible upon Form Load.

-Cheers
Snehal

**Comment by ghiscoding** [comment]
Hello again

Reading your new lines and maybe got some answers for some

1, 5) I pushed the new rev already, I edited my last post, you probably didn't see
3) I also do that often in my projects, what you have to do is simply make the disabled/enabled by using the `ngDisabled`, the library doesn't validate when the input is disabled. This is a very good example on the [Live Plunker Demo](http://plnkr.co/jADq7H), go down the page and see the last input at the bottom, there's a radio button to enable/disable the field, open the Validation Summary and then flip the radio button On and Off, you will see it getting validated or not depending on the state of the radio button.
4) Going further with previous explanation, I would suggest that you make your next field(s) enabled by using the `ngEnabled` and make it work with a formula inside it that will check the state of the first input. 
5) I never ever use the built-in AngularJS validation, I didn't like the fact that you have to write so much lines, so I decided to build my own library and never turn back to the built-in one, you use 1 or the other. The reason why the form is pre-populated with the `$error` is that I need to pre-validate all the inputs so that the Validation Summary gets filled, else it would be empty on page load which wouldn't help the user much... So yes it's normal that the `$error` is filled even though you made the `preValidation: false`, this last option is only meant for a visual option, it will still pre-validate each inputs and make them invalid in the background, it's a completely normal behavior, again the reason being that I need it for Validation Summary to work.

I know that 4) is probably not what you want, but it was just to show you that it's possible to do it with your own code. Adding that into the library might had too much complexity and at this point, I wouldn't know how to add it in the library. 

If you want to help and add new features to the library, I would be happy to accept any pull request.
Thanks

**Comment by tiwarisnehal** [comment]
Many thanks for your help and quick responses.
I will play around and try to get it working the way I wan to.

If I may any headway, I might make that pull request.
Cheers

**Comment by ghiscoding** [comment]
If that answers most of your questions, then please close this issue. If you ever get a pull request, it would be better to open a new one since this one here is a lot too generic. Thanks

**Comment by ghiscoding** [comment]
I was actually curious on how to do your number 4) and 5) and got it easily done. The Angular-Validation library is using exactly the same property as a regular AngularJS built-in library and so you can use the `$invalid` property of each field. For example let say you have a form named `form1` and 3 inputs `input1`, `input2`, `input3`. 

So let's start with an easy one, let say you want to enable `input2` when `input1` becomes valid. Just simply do the following
```html
<input type="text" name="input1" validation="alpha|required" />
<input type="text" name="input2"  validation="alpha|required" ng-disabled="form1.input1.$invalid" />
```
Now let say you want to enable `input2` only after `input1` is valid but then `input3` only after `input1` and `input2` are valid. You would do something similar to previous code but the input3 will hold a bigger check
```html
<input type="text" name="input1" validation="alpha|required" />
<input type="text" name="input2"  validation="alpha|required" ng-disabled="form1.input1.$invalid" />
<input type="text" name="input3"  validation="alpha|required" ng-disabled="form1.input1.$invalid || form1.input2.$invalid" />
```

I only tried with 2 inputs and it works great, the 3 inputs should work the way I wrote it, but still haven't tried it. So it's not that hard and it follows the Angular way. Everything that goes inside the `ngDisabled` will be interpreted and the `$invalid` property of each field is the best fit for this.

Hope that helps... no need for the library to do it, you can deal with it directly
