### ISSUE TITLE
Enhancement: Translation prefix

### ISSUE THREAD

**Issue by pnapieracz** [ghiscoding/angular-validation#51]
It'd be great to add translate prefix options. It helps to group translations.
It could be add here (I do not know is it proper place to did it):
validationCommon.js:
```javascript
        _globalOptions = {
          translatePrefix: null,

...

        var msgToTranslate = _globalOptions.translatePrefix ? (_globalOptions.translatePrefix + validator.message) : validator.message;
```

**Comment by ghiscoding** [comment]
Can you give more examples on the usage? I'm not sure to see it in action. Are they locale translation prefix? or is it prefix defined as an alternate text? Where would get the text basically...

**Comment by ghiscoding** [comment]
Please provide more details if you want this change. I would like to see more examples before making any changes.

**Comment by ghiscoding** [comment]
I will soon close this issue if I get no response from your side...

**Comment by Waniusza** [comment]
Actualy, I think it's great idea. Why?

Now I do project with many views that will be translated for few languages. 
To make translator's work easier, I decide to group i18n keys like that:

```
{
   "sidebar": { ... },
   "confirm" : { ... },
   "import" : {...},
  "INVALID_ALPHA": "Może zawierać tylko litery. ",
  "INVALID_REQUIRED": "Pole jest wymagane. ",
  "INVALID_INTEGER": "Musi być dodatnią liczbą całkowitą. ",
  "INVALID_MIN_NUM": "Musi być wartością numeryczną równą lub większą od {0}. ",
  "INVALID_MIN_CHAR": "Musi być długości co najmniej {0} znaków. "
}
```

It will be great to have something like:

```
{
   "sidebar": { ... },
   "confirm" : { ... },
   "import" : {...},
  "validation_error" : {
          "INVALID_ALPHA": "Może zawierać tylko litery. ",
          "INVALID_REQUIRED": "Pole jest wymagane. ",
          "INVALID_INTEGER": "Musi być dodatnią liczbą całkowitą. ",
          "INVALID_MIN_NUM": "Musi być wartością numeryczną równą lub większą od {0}. ",
          "INVALID_MIN_CHAR": "Musi być długości co najmniej {0} znaków. "
   }
}
```

So I do like pnapieracz wrote and set global option :
```
        $scope.$validationOptions = {
            // translation prefix used to group translations in json file
            translatePrefix: 'validation_error.',
           ...
       }
```

**Comment by ghiscoding** [comment]
So you will make a pull request with your code change soon?

**Comment by ghiscoding** [comment]
Having a second thought on the subject and I won't fix this one since your suggestion is completely valid. I actually strongly suggest to **not mix Angular-Validation translations** with your own translations as it is mentioned in my [Wiki - HOWTO Step by Step](https://github.com/ghiscoding/angular-validation/wiki/HOWTO---Step-by-Step#step5_2)

Since it is strongly recommended to create your own translations locales outside of the Angular-Validation translations (and not touch at all Angular-Validation translations). I see no benefits in doing translation prefix functionality. 

Angular-Translate already support [translation prefix](https://github.com/angular-translate/angular-translate/wiki/Asynchronous-loading) so please use that instead of adding in my own package.
