### ISSUE TITLE
checkFormValidity() requires a valid Angular Form

### ISSUE THREAD

**Issue by LennyLip** [ghiscoding/angular-validation#61]
http://plnkr.co/edit/lvXcG4m1WsXdhG4999TK?p=preview

return

"checkFormValidity() requires a valid Angular Form or $scope/vm object passed as argument to work properly, for example"

Don't understand, where the problem?

**Comment by LennyLip** [comment]
hm, obj.$validationSummary is undefined, and so wthat?

**Comment by ghiscoding** [comment]
You're missing the `AngularTranslate` configuration and AngularJS doesn't seem to tell you that the problem is there, but that's the problem anyway.

So in your plunker, you're missing this

```javascript
myApp.config(['$compileProvider', function ($compileProvider) {
    $compileProvider.debugInfoEnabled(false);
  }])
	.config(['$translateProvider', function ($translateProvider) {
	  $translateProvider.useStaticFilesLoader({
      prefix: 'https://rawgit.com/ghiscoding/angular-validation/master/locales/validation/',
      suffix: '.json'
    });
  	// load English ('en') table on startup
		$translateProvider.preferredLanguage('en').fallbackLanguage('en');
	}]);
```

That's all, the error goes away after that. I don't know why it's the Angular-Validation error that is thrown instead of Angular-Translate. Possibly because they didn't think about throwing errors on their side.

**Comment by LennyLip** [comment]
ups, my bad, many thanks!

**Comment by ghiscoding** [comment]
Welcome, it wasn't obvious at first, just too bad Angular-Translate doesn't return any error.
