### ISSUE TITLE
Support: Validating floating numbers of format- 20.11 (2 number & 2 decimal points)

### ISSUE THREAD

**Issue by roymj88** [ghiscoding/angular-validation#77]
Hi,

First of all thank-you so much for this validation module as its quite useful. I was wondering if there is a way to validate the floating numbers of format 
```
20.11 (2 number & 2 decimal points)
```
Thanks
Roy

**Comment by gsantiago** [comment]
You can use patterns:

```html
validation="pattern=/[0-9]{2}\.[0-9]{2}$/:alt=Invalid number"
```

**Comment by roymj88** [comment]
Adding the above:
```
<input type="text" class="form-control" ng-model="project.formData.price" validation="pattern=/[0-9]{2}\.[0-9]{2}$/:alt=Invalid number">
<span class="validation text-danger"></span>
```
doesnt seem to trigger the validation. 

Is there anything else that needs to be added?
Version i am using: 
```
angular-validation - v1.1 - 2014-05-02
```

**Comment by gsantiago** [comment]
Try to add a `name` attribute:
<input type="text" name="price" ...>

**Comment by roymj88** [comment]
Added `name` attribute, but no luck. Here is what happens to class when i add some text:

```
<input name="price" type="text" class="form-control ng-animate ng-pristine-remove ng-dirty-add ng-pristine-remove-active ng-dirty ng-dirty-add-active ng-invalid-remove ng-valid-add ng-invalid-validation-remove ng-invalid-remove-active ng-valid ng-valid-add-active ng-invalid-validation-remove-active ng-valid-validation" ng-model="project.formData.price" validation="pattern=/[0-9]{2}\.[0-9]{2}$/:alt=Invalid number" style="">
```

**Comment by gsantiago** [comment]
Try to add both, `name` and `ng-model` attributes.

**Comment by roymj88** [comment]
Actually both are there. 
```
<input name="price" type="text" class="form-control" ng-model="project.formData.price" validation="pattern=/[0-9]{2}\.[0-9]{2}$/:alt=Invalid number">
<span class="validation text-danger"></span>
```

**Comment by gsantiago** [comment]
Custom patterns are available since the version 1.3.35, but you are using an old version. Why don't you try to update it?

**Comment by ghiscoding** [comment]
@gsantiago, thanks for answering, looks like all your answers are correct.

@roymj88, if you want support please update to the latest version. I am not supporting older versions. For `Angular-Validation`, I am only looking forward, though I never remove previous features (so that it doesn't break people's code). If for whatever reasons you really have to stick with older version, then see the previous implementation [Wiki - Regex](https://github.com/ghiscoding/angular-validation/wiki/Regular-Expressions-(Regex)), it still works **BUT** as @gsantiago already said, I strongly suggest you to update (if you can), since a lot of new features and fixes were added since then.

Thanks

**Comment by ghiscoding** [comment]
Unless I'm wrong then this is a closed issue...
