### ISSUE TITLE
How to create custom functions with dynamic models?

### ISSUE THREAD

**Issue by shlomogoldstein** [ghiscoding/angular-validation#81]
How to access the model of an ng-repeat input in a custom function?

**Comment by ghiscoding** [comment]
From the library you can look into the folder `more-examples`, there are examples about dynamic form and dynamic input. For ngRepeat, you can also look at the main Plunker demo.

**Comment by patrickhigiro** [comment]
I could not find any example addressing this case:

view
```
<div ng-repeat="item in items">
   <div ng-model="item.value" validate="validation="custom:myValidation"></div>
```

ctrl
```
$scope.myValidation = function() {
  // how to access current item.value ?
}
```

**Comment by ghiscoding** [comment]
The `custom` function call for validation that you are showing is actually this: [Wiki - Custom Validation functions](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions) and there's also this one [Wiki - Remote Validation](https://github.com/ghiscoding/angular-validation/wiki/Remote-Validation-(AJAX)) if your validation is on your backend server.

I based myself on `Laravel` as well, since I liked their concept a lot, to build my validation lib. I just didn't like validation which AngularJS give in their docs with `ngMessage`, it creates a lot too many lines in your html form and doesn't support locale translation the good way... So that is how my lib was born. 

The name of `angular-validation` was already taken so I named mine with my Git username `angular-validation-ghiscoding`... Does that answer your question?

**Comment by shlomogoldstein** [comment]
I still do not know how to access the specific item of items in my ctrl validation function. I need to pass at least the index of my items array to be able to validate it. In your examples you always use models like vm.model.input1, I need to validate array items.

So, how can I pass the array item "item.value" to my validation function? Or how can I pass the $index of this "item" to my validation function?

```
<div ng-repeat="item in items">
   <div ng-model="item.value" validation="custom:myValidation:$index"></div>
´´´


```
$scope.myValidation = function($index) {
  // i can address my item in items via $index
}
´´´

**Comment by ghiscoding** [comment]
ah I see now. I am **not currently supporting** arguments for custom function call. I implemented the `custom` and `remote` by just finding the function name inside the scope and run it. I just didn't think about arguments at that time.

I'm currently working on another functionality.
I could possibly revised the code for the `custom` & `remote` validators at the same time. I could possibly change the function find in scope with this instead `scope.$eval()`. I'll have to test it out and If that work, you could then put whichever arguments you wish. The call would be like any other function calls, so like this: `validation="custom:myValidation($index)"` and don't forget that this is a Validator, so you can still mix it with any other validator `validation="custom:myValidation($index)|required|alpha"`

So if that work, it could possibly be in the next revision coming soon.

As for the name, you could call that custom Directive or Service (since I support both) or even a Module (you could find some more here: [ngModules.org](http://ngmodules.org/))

**Comment by ghiscoding** [comment]
Added possibility of passing arguments/parameters to Custom & Remote validators. So you could now call it this way: `validation="custom:myValidation($index)"`, it remains a validators and so you can still mix it with other validators `validation="custom:myValidation($index)|required"`

Try it out and let me know if you get any problem. 

Pushed in latest version [1.4.14](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.14)

**Comment by shlomogoldstein** [comment]
Amazing thank you!
