### ISSUE TITLE
Custom styling of input

### ISSUE THREAD

**Issue by qbunia** [ghiscoding/angular-validation#83]
Hello,

My problem is that my inputs whenever I validate them I have to add a span with glyphicon to each input depending of its valid or not. I could use callback for each input but I guess its not how it should be done. So basicly I need some kind of global api to have access to each element that is beeing validated.

Would it be possible for you to make that feature?

**Comment by ghiscoding** [comment]
You might be able to use this [Wiki - Custom Validation functions](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions) and from there do your extra manipulation depending if it's valid or not. 

You could also use directly the `$valid` or `$invalid` variable of the input to do what you want. For example
```html
<form name="vm.form1">
  <input name="firstname" ng-model="vm.user.firstname" />
  <div ng-show="vm.form1.firstname.$valid">Something to display</div>
</form>
```

I won't add a new feature since you probably can use what is already built in Angular to do what you want.

**Comment by ghiscoding** [comment]
no feedback, I'm closing the issue...
