### ISSUE TITLE
How disable debounce globally, not in controller

### ISSUE THREAD

**Issue by shlomogoldstein** [ghiscoding/angular-validation#87]
The debounce option can be set via

         new validationService({ controllerAs: vm, debounce: 0 });

in a controller. How can I set the debounce to 0 globally for my whole app?

**Comment by ghiscoding** [comment]
That is a global option, it should technically do it globally to your app. Though, I do a reset when changing your route, there's a way to bypass that reset if you really wish to, but it's preferable not to do that because you really affect all your App with all the global options.

**Comment by shlomogoldstein** [comment]
I think a global option should really do that - affect all your app. Could you tell me how to bypass a state change?

**Comment by ghiscoding** [comment]
Everything is in the [Wiki - Global Options](https://github.com/ghiscoding/angular-validation/wiki/Global-Options) and the property you want is `resetGlobalOptionsOnRouteChange: false` but it's not recommend to turn Off especially if you use Validation Summary, because that variable also won't be reset and you end up with errors of previous route (if there was) which is why I said it's not good to use... but anyway try it out, I'm closing this issue.
