### ISSUE TITLE
'checked' rule description

### ISSUE THREAD

**Issue by Waniusza** [ghiscoding/angular-validation#89]
Hi ! 
Firstly, thanks for your great job! :+1: 

I see you added rule  'checked', but it's not described how to use it.
I want to use it with checkbox, but validator force me to use text type.

Can you give any sample how to do that and/or write how to validate checkbox?

Thank,
Janusz

**Comment by ghiscoding** [comment]
Hello,
I didn't add `Checked`, someone else did and didn't provide details which is also why it's not part of my official list. It probably doesn't work actually since a checkbox can provide `true` but also `checked`. 

If you just want to make sure that the checkbox is checked, then you could simply use `required` it basically does the same but with different message and if you don't like that message then you could use an alternate message with `alt:`

Also if you like my package/library, you can also click on the **Star** on top, always happy to have more people using it ;)

**Comment by Waniusza** [comment]
I stared it days ago! :)

You was right, required works great with checkbox type, and to force checking we can add 'accepted' validation :)
If someone will got similar problem, there is how it can be done:

<div class="form-group">
    <div class="col-md-7 col-md-offset-3">
        <div class="checkbox inline">
            <input type="checkbox"   id="checkbox_id" ng-model="form.agreement" validation-error-to="#myErrorId" name="terms" validation="required|accepted">
            <label for="checkbox_id"> Accept <a ui-sref="app.terms" target="_blank">Terms</a> 
            </label>
            <div id="myErrorId" class="validation text-danger"></div>
        </div>
    </div>
</div> 

Thanks! It's solved :+1:

**Comment by Waniusza** [comment]
Sorry, didn't get message styling :)

```
<div class="form-group">
    <div class="col-md-7 col-md-offset-3">
        <div class="checkbox inline">
            <input type="checkbox"   id="checkbox_id" ng-model="form.agreement" validation-error-to="#myErrorId" name="terms" validation="required|accepted">
            <label for="checkbox_id"> Akceptuję <a ui-sref="app.terms" target="_blank">Warunki użytkowania</a> 
            </label>
            <div id="myErrorId" class="validation text-danger"></div>
        </div>
    </div>
</div> 
```

**Comment by ghiscoding** [comment]
So we can close the issue then?
