### ISSUE TITLE
IBAN Numbers check failure from various country

### ISSUE THREAD

**Issue by pabx06** [ghiscoding/angular-validation#93]
I tryed iban number from diffrents country : 
http://www.mobilefish.com/services/random_iban_generator/random_iban_generator.php
they are failling to pass

**Comment by ghiscoding** [comment]
Hi sorry but I never use the IBAN anywhere, so if you can fix it yourself by doing a pull request then I would be happy. The pattern is located in the [validation-rules.js](https://github.com/ghiscoding/angular-validation/blob/master/src/validation-rules.js) with the rule of
`/^[a-zA-Z]{2}\d{2}\s?([0-9a-zA-Z]{4}\s?){4}[0-9a-zA-Z]{2}$/i`

So please make a pull request with your fix. Thanks

**Comment by ghiscoding** [comment]
The only other IBAN Regex I found was the following and is mentioned it's pattern for All IBAN.
```javascript
[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[0-9]{7}([a-zA-Z0-9]?){0,16}
```

We don't use IBAN in North America, so I can't help you more. 
Please provide feedback if you want this fix.

**Comment by pabx06** [comment]
Thanks. I will try it tonight . i will let you know . why not include
various iban number from the URL un the test unit ?

**Comment by ghiscoding** [comment]
As I mentioned earlier, we actually don't use IBAN in North America where I am. The only reason I had it in my list of Validators is simple because I copied a few of these Validators from another tool and the IBAN was in there. I never ever used IBAN and don't know at all how it works. 

So if you have a proper Regex for it, then please provide, if not I might end up removing it completely from the available Validators. I never used it and will never use it... so it's all in your hand ;)  

And quickly looking at it, we might actually not be able to have a Regex to fit all, since that seems to change from each country as displayed in this web page: [IBAN/BBAN Regular Expression Patterns](http://ht5ifv.serprest.pt/extensions/tools/IBAN/)

**Comment by pabx06** [comment]
Yes but it has à checksum. Like credit card . il will try to make send a
patch. IBAN is replacing crédit card un popularity un europe. And has lower
fée.

**Comment by ghiscoding** [comment]
The problem is that for my Validator to work, it needs to be a Regex pattern, and if you can't do it via a Regex then it won't work. I don't see any ways of dealing with a checksum inside a Regex.

The other option you might have is through a [custom javascript function](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions), but you will have to do it on your own. 

Do you speak French? Moi oui...

**Comment by pabx06** [comment]
Le problème j'aimerais bien intégré l'IBAN BIC dans ce projet.

bower install iban. et ou npm install iban

var IBAN=require('iban');

console.log(IBAN.isValid('BE68539007547034')); // true
console.log(IBAN.isValid('AL66565657692576393682655152'));

apres http://browserify.org/

sinom installer un autre projet :  https://github.com/mmjmanders/ng-iban


j'abandonne j'ai pas reussit a installer dans ton code



2015-12-15 23:26 GMT+01:00 Ghislain B. <notifications@github.com>:

**Comment by ghiscoding** [comment]
Tu peux utiliser ton outil IBAN externe en passant par Angular-Validation `custom` et tu peux aussi ajouter d'autres Validateurs comme par exemple `required`

```html
<input type="text" class="form-control"
            name="iban"
            ng-model="vm.model.iban"
            validation="custom:vm.myIbanCheck(vm.model.iban)|required" />
```
Ensuite dans ton controller, appelle ta fonction custom
```javascript
myApp.controller('Ctrl', function () {
    var vm = this;

    vm.myIbanCheck = function(inputModel) {
         return IBAN.isValid(inputModel);
    }
}
```

Je n'ai pas tester mais ça devrait fonctionner. Dis-moi si ça fonctionne et ensuite je l'ajouterai dans la documentation Wiki.

**Comment by pabx06** [comment]
je suis de strasbourg. je vais checker. a plus . c'est rare les gens qui
font de l'angular en france

Le 17 décembre 2015 à 16:07, Ghislain B. <notifications@github.com> a écrit
:

**Comment by ghiscoding** [comment]
Je suis de Montréal, j'ai juste vu que tu avais mis beaucoup d'accents alors j'ai imaginé que tu parlais Français :P

**Comment by ghiscoding** [comment]
Est-ce que ca fonctionne? J'aimerais pouvoir fermer ce ticket...

**Comment by pabx06** [comment]
J'ai pas encore testé mais c'est pas mal lourd , mon app . et j'ai une
erreur avec angular après minification de l'App uniquement je pense que ça
provient du service de traduction ...

**Comment by ghiscoding** [comment]
For IBAN validation, I now suggest to use [Wiki - Custom Validation](https://github.com/ghiscoding/angular-validation/wiki/Custom-Validation-functions) with the external library of [Github - arhs/iban.js](https://github.com/arhs/iban.js). 

I updated the [Custom Validation - Plunker Demo](http://plnkr.co/GrZeyD) and also the code sample found under the folder [more-examples/customValidation](https://github.com/ghiscoding/angular-validation/tree/master/more-examples/customValidation)

Merci de ton support, mes pages Wiki sont a jour sur le sujet :)
