### ISSUE TITLE
Possible to use "or"?

### ISSUE THREAD

**Issue by pcxstephan** [ghiscoding/angular-validation#98]
Hi!

I want to validate an IP address field as either IPv4 *OR* IPv6. Using the directive I tried validate="ipv4|ipv6" but this makes it so that the field has to be valid for IPv4 *AND* IPv6. Is this possible to do without writing a custom validation function?

**Comment by ghiscoding** [comment]
Angular-Validation is looping through all Validators in sequence and they all need to be valid for the field to become valid itself. Basically there is currently no such thing as either "or" validator.

In your case, it's probably best to use `pattern` validator and define it as either or will pass.

**Comment by ghiscoding** [comment]
Ok so I made a change and added your request into the latest release [v1.4.18](https://github.com/ghiscoding/angular-validation/releases/tag/v1.4.18)

You can now use a new attribute named `valid-require-how-many` to simulate "this Validator OR that Validator". So for example, if you want to validate IPV4 or IPV6, you could then do this
```html
<input type="text" 
       name="input2"
       ng-model="input2"
       validation="ipv4|ipv6"
       valid-require-how-many="1" />
```
But please note that if you include the `required` Validator, you will need to count +1 since you want (IPV4 or IPV6) and (required), so how many do we require for the field to be valid in that case? Answer is 2. Then if we take the same example but also include the `required`, it becomes this
```html
<input type="text" 
       name="input2"
       ng-model="input2"
       validation="ipv4|ipv6|required"
       valid-require-how-many="2" />
```

You can see the new description inside the [Wiki - Valid-Require-How-Many](https://github.com/ghiscoding/angular-validation/wiki/Inputs-(local-options)#valid-require-how-many)

**Comment by pcxstephan** [comment]
Great explanation and works like a charm! Thank you!
